-- Seed data for local development.
-- Add INSERT statements here to pre-populate tables when running `npx supabase db reset`.
--
-- Note: the avatars storage bucket and its RLS policies are created by
-- supabase/migrations/20240102000000_create_avatars_bucket.sql so that
-- `supabase db push` also applies them to the remote database.
